// Generated by make-ip-conf.pl
// ens33 192.168.15.102 00:0c:29:9d:0f:af
// ens37 192.168.16.102 00:0c:29:9d:0f:b9

// Shared IP input path and routing table
ip :: Strip(14)
    -> CheckIPHeader(INTERFACES 192.168.15.102/255.255.255.0 192.168.16.102/255.255.255.0)
    -> rt :: StaticIPLookup(
	192.168.15.103/255.255.255.255 192.168.15.103 0,
	192.168.16.103/255.255.255.255 192.168.16.103 1,
	0.0.0.0/0.0.0.0 192.168.16.103 1);

// Input and output paths for ens33
c0 :: Classifier(12/0800, -);
FromDevice(ens33) -> c0;
out0 :: Queue(200) -> todevice0 :: ToDevice(ens33);
c0[0] -> ip;
c0[1] -> Discard;

// Input and output paths for ens37
c1 :: Classifier(12/0800, -);
FromDevice(ens37) -> c1;
out1 :: Queue(4000) -> todevice1 :: ToDevice(ens37);
c1[0] -> ip;
c1[1] -> Discard;

// Forwarding path for ens33
rt[0] -> DropBroadcasts
    -> dt0 :: DecIPTTL
    -> out0;
dt0[1] -> ICMPError(192.168.15.102, timeexceeded) -> rt;

// Forwarding path for ens37
rt[1] -> DropBroadcasts
    -> FixIPSrc(192.168.16.102)
    -> dt1 :: DecIPTTL
    -> out1;
dt1[1] -> ICMPError(192.168.16.102, timeexceeded) -> rt;
